indexpage/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('indexpage.views',
    url(r'^$', 'show_index_page', name='home'),
    url(r'^ajax/$', 'send_email_ajax', name='ajax_email'),
    url(r'^order/(?P<form_name>[-\w]+)/$', 'show_form', name='show_form'),
    url(r'^order/studwork/$', 'show_form', name='show_work_form'),
    url(r'^page/(?P<slug>[-\w]+)/$', 'show_bottom_page', name='menu'),
    url(r'^contacts/$', TemplateView.as_view(template_name='contacts.html'), name="contacts"),
    url(r'^getjob/(?P<form_attr>[-\w]+)/$','show_vakansy_form', name="getjob"),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
)

visitsite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from filebrowser.sites import site

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^grappelli/', include('grappelli.urls')),
	url(r'^admin/filebrowser/', include(site.urls)),
	url('',include('indexpage.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    
)

indexpage/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.flatpages.models import FlatPage
from tinymce import models as tinymce_model
from sorl.thumbnail.fields import ImageField
from django.utils.translation import ugettext_lazy as _
from chooses import *

class Parent(models.Model):
	name = models.CharField(max_length=100,verbose_name=u'Название')
	def __unicode__(self):
		return unicode(self.name)
	class Meta:
		verbose_name = u'Категория'
		verbose_name_plural = u'Категория'


class Menubottom(models.Model):
	name = models.ForeignKey(Parent)
	title = models.CharField(max_length=100,verbose_name=u'Название')
	slug = models.SlugField(verbose_name=u'Красивый адрес')
	text = models.TextField(verbose_name=u'Текст')

	def __unicode__(self):
		return unicode(self.title)

	class Meta:
		verbose_name = u'Нижнее меню'
		verbose_name_plural = u'Нижнее меню'

	def get_absolute_url(self):
		return "/page/%i/" % self.slug


class Uslugi(models.Model):
	none = 'none'
	studwork = 'studwork'
	upgradeunic = 'upgradeunic'
	electro = 'electro'
	blank = 'blank'
	FORMA = (
		(none, 'Без ссылки'),
        (studwork, 'Учебные работы'),
        (upgradeunic, 'Повышение уникалльности'),
        (electro, 'Работа с электронными документами'),
        (blank, 'Бланк перевода'),
    )
	title = models.CharField(max_length=30,verbose_name=u'Заголовок')
	background_class = models.CharField(max_length=2,verbose_name=u'Фоновый цвет (b1,b2..)')
	price = models.CharField(max_length=30,verbose_name=u'Цена')
	day = models.CharField(max_length=10,verbose_name=u'Срок исполнения')
	form_name = models.CharField(max_length=300,choices = FORMA,verbose_name=u'Выводимая форма',null=True,blank=True)
	link = models.ForeignKey(Menubottom,verbose_name=u'Связанная страница',null=True,blank=True)
	def __unicode__(self):
		return u'%s %s' % (self.title, self.background_class)

	class Meta:
		verbose_name = u'Услуга'
		verbose_name_plural = u'Услуги'

	def get_absolute_url(self):
		return reverse('show_form', args=[str(self.form_name)])



class UpgradeUnic(models.Model):
	hand = 'hand'
	auto = 'auto'
	SPOSOB_OBRABOTKI = (
        (hand, 'Ручной(рерайтинг)'),
        (auto, 'Механический'),
    )
	name = models.CharField(max_length=100,verbose_name=u'Имя',null=True,blank=True)
	phone = models.CharField(max_length=100,verbose_name=u'Телефон')
	email = models.CharField(max_length=100,verbose_name=u'Еmail',null=True,blank=True)
	sposob = models.CharField(max_length=100,verbose_name=u'Обработка текста',choices=SPOSOB_OBRABOTKI)
	original_start = models.CharField(max_length=100,verbose_name=u'Оригинальность текущая',null=True,blank=True)
	original_finish = models.CharField(max_length=100,verbose_name=u'Желаемая оригинальность')
	date = models.CharField(max_length=100,verbose_name=u'Дата получения')
	comment = models.CharField(max_length=100,verbose_name=u'Комментарий',null=True,blank=True)
	document = models.FileField(upload_to='files',verbose_name=u'Файл',null=True,blank=True)

	def __unicode__(self):
		return unicode(self.name)

	class Meta:
		verbose_name = u'Повышение уникалльности'
		verbose_name_plural = u'Повышение уникалльности'
	
	def get_absolute_url(self):
		return "/upgradeunic/%d"  % self.pk

class ElectroDocument(models.Model):
	printtext = 'printtext'
	handtext = 'handtext'
	edit = 'edit'
	TYPE_WORK = (
        (printtext, 'Cо сканированного печатного текста'),
        (handtext, 'со сканированного рукописного текста'),
        (edit, 'Редактирование/Корректура'),
    )
	name = models.CharField(max_length=100,verbose_name=u'Имя',null=True,blank=True)
	phone = models.CharField(max_length=100,verbose_name=u'Телефон')
	email = models.CharField(max_length=100,verbose_name=u'Еmail',null=True,blank=True)
	work = models.CharField(max_length=100,verbose_name=u'Тип работы',choices=TYPE_WORK,null=True,blank=True)
	date = models.CharField(max_length=100,verbose_name=u'Дата получения')
	comment = models.CharField(max_length=100,verbose_name=u'Комментарий',null=True,blank=True)
	document = models.FileField(upload_to='files',verbose_name=u'Файл',null=True,blank=True)

	def __unicode__(self):
		return unicode(self.name)

	class Meta:
		verbose_name = u'Работа с электронными текстами'
		verbose_name_plural = u'Работа с электронными текстами'

	def get_absolute_url(self):
		return "/electrodocument/%d"  % self.pk

class TranslateBlank(models.Model):
	name = models.CharField(max_length=100,verbose_name=u'Имя',null=True,blank=True)
	phone = models.CharField(max_length=100,verbose_name=u'Телефон')
	email = models.CharField(max_length=100,verbose_name=u'Еmail',null=True,blank=True)
	original_language = models.CharField(max_length=100,verbose_name=u'Язык исходного текста')
	finish_language = models.CharField(max_length=100,verbose_name=u'Перевести на')
	date = models.CharField(max_length=100,verbose_name=u'Дата получения')
	comment = models.CharField(max_length=100,verbose_name=u'Комментарий',null=True,blank=True)
	document = models.FileField(upload_to='files',verbose_name=u'Файл',null=True,blank=True)

	def __unicode__(self):
		return unicode(self.name)

	class Meta:
		verbose_name = u'Бланк для переводов'
		verbose_name_plural = u'Бланк для переводов'

	def get_absolute_url(self):
		return "/translateblank/%d"  % self.pk


class Work(models.Model):
	name = models.CharField(max_length=100,verbose_name=u'Название')

	def __unicode__(self):
		return unicode(self.name)

	class Meta:
		verbose_name = u'Виды работ'
		verbose_name_plural = u'Виды работ'


class StudWork(models.Model):
	none = 'none'
	krugl = 'krugl'
	podstr = 'podstr'
	kvadtat = 'kvadtat'
	SNOSKI = (
        (none, 'Нет'),
        (krugl, 'Круглые скобки'),
        (podstr, 'Подстрочные'),
        (kvadtat, 'Квадратные'),
    )
	type_work = models.ForeignKey(Work,verbose_name=u'Тип работы')
	university = models.CharField(max_length=100,verbose_name=u'Университет',null=True,blank=True)
	topic = models.CharField(max_length=100,verbose_name=u'Тема')
	item = models.CharField(max_length=100,verbose_name=u'Название предмета',null=True,blank=True)
	date = models.CharField(max_length=100,verbose_name=u'Дата сдачи',null=True,blank=True)
	level = models.CharField(max_length=100,verbose_name=u'Уровень уникальности',null=True,blank=True)
	page = models.CharField(max_length=100,verbose_name=u'Количество страниц',null=True,blank=True)
	note = models.CharField(max_length=100,verbose_name=u'Наличие сносок',choices=SNOSKI,null=True,blank=True)
	name = models.CharField(max_length=100,verbose_name=u'Имя',null=True,blank=True)
	phone = models.CharField(max_length=100,verbose_name=u'Телефон')
	email = models.CharField(max_length=100,verbose_name=u'Еmail',null=True,blank=True)
	comment = models.CharField(max_length=100,verbose_name=u'Комментарий',null=True,blank=True)
	document = models.FileField(upload_to='files',verbose_name=u'Файл',null=True,blank=True)

	def __unicode__(self):
		return self.topic

	class Meta:
		verbose_name = u'Учебные работы'
		verbose_name_plural = u'Учебные работы'

	def get_absolute_url(self):
		return "/studwork/%d"  % self.pk


class Slider(models.Model):
    title = models.CharField(_(u'заголовок'), blank=True, max_length=250, help_text=_(u'Рабочее название для админки.'))
    show_on = models.CharField(_(u'показывать на'), default=u'main', max_length=250,
                               help_text=_(u'принадлежность к странице, на которой будет находиться слайд'),
                               choices=(("main", "главной странице (580×300)"),))
    image = ImageField(_(u'изображение'), upload_to='slider')
    name = models.CharField(_(u'название'), blank=True, max_length=250, help_text=_(u'будет показываться при наведении на слайд; максимум 250 символов.'))
    url = models.CharField(_(u'ссылка'), blank=True, max_length=10000)
    target = models.BooleanField(_(u"открывать ссылку в новом окне"), default=False)
    display = models.BooleanField(_(u'отображать'), default=True)
    position = models.IntegerField(_(u'позиция'), default=100, help_text=_(u'номер для сортировки слайдов'))

    class Meta:
        ordering = ("-position", "show_on", )
        verbose_name = u"слайд"
        verbose_name_plural = u'слайды'

    def __unicode__(self):
        return u'%s: %s' % ( self.show_on, self.title)



class Node(models.Model):
    vname = models.CharField(max_length=150)
    MText = models.TextField()
    PubDate = models.DateTimeField()
 
    class Meta:
        verbose_name = 'Node'
        verbose_name_plural = 'Nodes'
 
    def __unicode__(self):
        return self.vname


#Vakansy model for vakansy form
class Vakansy(models.Model):
        #Общая инфа
        name = models.CharField(verbose_name=_(u"Имя"),max_length=100)
        surname = models.CharField(verbose_name=_(u"Фамилия"),max_length=100)
        father = models.CharField(verbose_name=_(u"Отчеcтво"),max_length=100)

        #Где живет
        city = models.CharField(verbose_name=_(u"Город проживания"),max_length=100)
        phone = models.CharField(verbose_name=_(u"Телефон"),max_length=100)
        icq = models.CharField(verbose_name=_(u"ICQ"),max_length=100,blank=True)
        skype = models.CharField(verbose_name=_(u"SKYPE"),max_length=100,blank=True)
        email = models.EmailField(verbose_name=_(u"E-mail"),max_length=100)

        #Образование
        vuz = models.CharField(verbose_name=_(u"Название ВУЗа"),max_length=100)
        fac = models.CharField(verbose_name=_(u"Факультет"),max_length=100,blank=True,help_text=u"suka")
        year_finish = models.CharField(verbose_name=_(u"Год окончания"),max_length=100)
        status = models.CharField(verbose_name=_(u"Статус"),choices=STATUS,max_length=100)

templates/alone.html
{% extends "index.html" %}
{% block main %}
	<main>
		<div class="content text">
			<h1>{{ item.title }}</h1>
			{{ item.text|safe }}
		</div>
	</main>	
{% endblock %}

templates/contacts.html
{% extends "index.html" %}
<!DOCTYPE html>
	{% block title %}<title>Контакты</title> {% endblock %}
{% block main %}
	<main>		
		<div class="content contacts">
			<div class="con1">
				<h2>Звоните нам:</h2>
				<p>+7 (4932) 50-60-50</p>
				<p class="image"><img src="{{STATIC_URL}}images/phone.png" alt=""></p>				
			</div>
			<div class="con2">
				<h2>Почта</h2>
				<p><a href="info@studacademia.ru">info@studacademia.ru</a><br>жалобы и предложений
				<a href="mailto:mnenie@studacademia.ru">mnenie@studacademia.ru</a></p>
				<p class="image"><img src="{{STATIC_URL}}images/email.png" alt=""></p>		
			</div>
			<div class="con3">
			<h2>Наш адрес</h2>
				<p>г.Иваново <br> ул. Советская, д.22 <br> офис 306</p>
				<p class="image"><img src="{{STATIC_URL}}images/www.png" alt=""></p>		
			</div>
			<div class="con4"><script type="text/javascript" src="//vk.com/js/api/openapi.js?105"></script>

<!-- VK Widget -->
<div id="vk_groups"></div>
<script type="text/javascript">
VK.Widgets.Group("vk_groups", {mode: 0, width: "220", height: "200", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 19929911);
</script></div> 
			
		</div>	
	</main>
{% endblock %} 

templates/index.html
{% load utils %}
{% load flatblock_tags %}
{% load thumbnail %}
<!DOCTYPE html>
<html>
<title>Студакадемия</title>
	<meta charset="utf-8" />
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<meta name="keywords" content="" />
	<meta name="description" content="" />


	{% block css %}<link href="{{STATIC_URL}}css/style.css" rel="stylesheet">{% endblock %}
	{% block js %}
		<script src="http://code.jquery.com/jquery-1.8.1.min.js"></script>
		<script src="{{STATIC_URL}}js/main.js"></script>
		<script src="{{STATIC_URL}}js/jquery.bxslider.js"></script>
		<script src="{{STATIC_URL}}js/tytabs.jquery.min.js"></script>
	{% endblock %}
	{% block ext %}{% endblock %}
</head>

{% block body %}
<body>
<div id="loader"><span>Загружаю...</span></div>
<div class="wrapper">
{% block head_menu %}
	<nav>
		<div class="nav">
			<ul>
				{% flatpage_menu %}	                                
			</ul>
		</div>
	</nav>
{% endblock %}
	<header>
		<div class="header">
			<a href="/"><img src="{{STATIC_URL}}images/logo.png" alt="Stud Academia. Качество. Ответственность. Профессионализм."></a>
			<div class="contact">
				<h2>info@studacademia.ru</h2>
				<p></p>
				<h2>+7(4932)-50-60-50</h2>		
			</div>		
		</div>
	</header>
	{% block main %}
	<main>		
		<section>
			<div class="content">
				<div class="banner">
				{% if slider %}
					<div class="slidePic">
						<ul class="bxslider">
						{% for slide in slider %}
						  <li><a href="{{ slide.url }}"{% if slide.target %} target="_blank"{% endif %}>
		                    {% thumbnail slide.image '580x290' upscale=False  as im %}
		                        <img src="{{ im.url }}" title="{{ slide.name }}" alt="{{ slide.name }}">
		                    {% endthumbnail %}
                    		<span class="border"></span></a></li>
                    	{% endfor %}
						</ul>
					</div>
				{% else %}
					<img src="{{STATIC_URL}}images/men.png" alt="">
					<div class="sale">
						<h3>Получи скидку 20%</h3>
						<p>на все виды наших услуг <br> только сегодня, до конца дня!</p>
						<a href="{% url 'show_work_form' %}">Получить</a>
					</div>
				{% endif %}
					<div class="anketa">
						<form name="work_price" id="work_price" action="/ajax/">
							<h4>Срочная заявка</h4>
							<input name="name"						
								value="Ваше имя?"
								type="text"
								onfocus="if (this.value=='Ваше имя?') this.value='' "
								onblur="if (this.value==''){this.value='Ваше имя?'}" 						
							>
							<input	name="phone"						
								value="Номер телефона (+7ХХХХХХХ)"
								type="text"
								onfocus="if (this.value=='Номер телефона (+7ХХХХХХХ)') this.value='' "
								onblur="if (this.value==''){this.value='Номер телефона (+7ХХХХХХХ)'}" 			
							>
							<input name="subject"
								class="les"
								value="Название работы"
								type="text"
								onfocus="if (this.value=='Название работы') this.value='' "
								onblur="if (this.value==''){this.value='Название работы'}" 			
							>
							<div class="error">&nbsp;</div>
							<a> <input type="button" id="price" value="Узнать стоимость"></a>

						</form> 
					</div>	
				</div>				
			</div>
		</section>
		<div class="content blocks">
		{% for single in uslugi %}
				{% if single.link %}
					<a  class="block" href="/page/{{ single.link.slug }}">
				{% else %}
					<a   class="block" href="{{ single.get_absolute_url }}">
				{% endif %}
				<h3>{{ single.title}}</h3>
				<div class="{{ single.background_class }}"></div>
				<i><span>{{ single.price }}</span></i>
				<b><span>{{ single.day }}</span></b>
				{% if single.link %}
					<p href="/page/{{ single.link.slug }}">Подробнее</p>
				{% else %}
					<p href="{{ single.get_absolute_url }}">Заказать</p>
				{% endif %}
			</a>	
		{% endfor %}
		</div>	
		<div class="lenta">
			<div class="content">		
				<div class="left">
					<p>Контроль качества,<br> антиплагиат — от 80%</p>
					<p>Бесплатная доработка заказов*</p>
				</div>
				<div class="center">
					<h3>Наши преимущества</h3>
					<p>Гарантия на работу 2 месяца</p>
				</div>
				<div class="right">
					<p>Профессиональная <br> команда преподавателей</p>
					<p>Скидки постоянным клиентам</p>
				</div>
			</div>
		</div>		
	</main>
	{% endblock %}
</div>
{% block footer %}
<footer>
	{% flatblock "google_analitics"  %}
	<div class="row1">
		<div class="footer">
			{% bottom_menu %}
			<div class="col3">		
				<h3>Остались вопросы? Звоните!<br>info@studacademia.ru<br><span>+7 (4932)</span> 50-60-50</h3>
				<h3 class="f1">Хотите заказать работу?</h3>
				<a href="{% url 'show_work_form' %}">Заказать</a>
			</div>
		</div>
	</div>
	<div class="row2">
		<div class="footer">
			<div class="r1"><p>® Все права защищены <br> © visitsite, 2013</p></div>
			<div class="r2"><a href="#" target="_blank"><img src="{{STATIC_URL}}images/vk.png" alt="vk"></div>
			<div class="r3">
				<p>Создание сайта:
					<a href="http://place-start.ru/" target="_blank">
						<img src="{{STATIC_URL}}images/placestart.png" alt="Разработка сайтов, компания Place-start">
					</a>
				</p>
			</div>
		</div>
	</div>
</footer>
{% endblock %}
</body>
{% endblock %}
</html>


templates/order.html
{% extends "index.html" %}
	{% block title %}<title>Заказ рыботы</title>{% endblock %}
	{% block ext%}
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
  	<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  	<script src="{{STATIC_URL}}js/ru.js"></script>
  	<script>
  $(function() {
    $( "#id_date" ).datepicker();
	  $.datepicker.setDefaults({
	  showOn: "both",
	  buttonImageOnly: true,
	  buttonImage: "calendar.gif",
	  buttonText: "Calendar",
	});
	$.datepicker.setDefaults( $.datepicker.regional[ "ru" ] );
  });
  </script>
{% endblock %}
{% block main %}
	{% if thanks %}<h1 class="success">Спасибо.Ваш заказ принят</h1>
	<script>
	$(document).ready(function(){
		function go_on(){
			document.location.href = '/';
		}
		setTimeout(go_on,5000);
	});
	  </script>
	{% else %}
	<main>
	<div class="content order">
		<h1>Заказ работы</h1>

		<form name="order_form" action="" method="POST"  enctype="multipart/form-data">{% csrf_token %}
		<input type="hidden" name="action" value="order"/>
			{% for field in form %}
				{% if field.errors %}
					<li class="placeholder">{{ field.label_tag }}{{ field }}</li>
				{% else %}
					<li>{{ field.label_tag }}{{ field }}</li>
				{% endif %}
			{% endfor %}
			 <input type="submit" value="Заказать">
		</form>
	</div>	
	</main>
	{% endif%}
{% endblock %}

templates/text.html
{% extends "index.html" %}
{% block main %}
	<main>
		<div class="content text">
			<h1>{{ flatpage.title }}</h1>
			{{ flatpage.content }}
		</div>
	</main>	
{% endblock %}

templates/vakansy.html
{% extends "index.html" %}
	{% block main %}
	<main>
	{% if thanks %}
		<h1 class="success">Спасибо.Ваш заказ принят</h1>
		<script>
		$(document).ready(function(){
			function go_on(){
				document.location.href = '/';
			}
			setTimeout(go_on,5000);
		});
		  </script>
	{% else %}
	{% if which_form %}
			{% if which_form == 'repetitor' %}
				<div class="content order">
				<h1>Анкета репетитора</h1>
					<form name="" action="" method="POST"  enctype="multipart/form-data">{% csrf_token %}
						{% for field in form %}
							{% if field.name == 'name' %}<h1 class="prepare">Ваши ФИО</h1>{% endif %}
							{% if field.name == 'city' %}<h1 class="prepare">Контакты</h1>{% endif %}
							{% if field.name == 'vuz' %}<h1 class="prepare">Сведения об образовании</h1>{% endif %}
							{% if field.name == 'stage' %}<h1 class="prepare">Педагогический стаж</h1>{% endif %}
							{% if field.name == 'subjects' %}<h1 class="prepare">Преподаваемые Вами предметы</h1>{% endif %}
							{% if field.name == 'doschool' %}<div class="checkbox_div"><h1 class="prepare">Укажите программу репетиторства, которую Вы хотели бы вести</h1>{% endif %}
							{% if field.name == 'zero_ur' %}</div><h1 class="prepare">Уровень подготовленности ученика</h1>{% endif %}
							{% if field.name == 'mesto_this' %}<h1 class="prepare">Место проведения занятий</h1>{% endif %}
							
							{% if field.errors %}
								<li class="placeholder">{{ field.label_tag }}{{ field }}</li>
							{% else %}
								<li>{{ field.label_tag }}{{ field }}</li>
							{% endif %}

						{% endfor %}
				 	<input class="submit_button" type="submit" value="Заказать">
					</form>
				</div>
			{% endif %}

			{% if which_form == 'manager' %}
				<div class="content order">
				<h1>Анкета менеджера</h1>
					<form name="" action="" method="POST"  enctype="multipart/form-data">{% csrf_token %}
						{% for field in form %}
							{% if field.name == 'name' %}<h1 class="prepare">Ваши ФИО</h1>{% endif %}
							{% if field.name == 'city' %}<h1 class="prepare">Контакты</h1>{% endif %}
							{% if field.name == 'vuz' %}<h1 class="prepare">Сведения об образовании</h1>{% endif %}
							
							{% if field.errors %}
								<li class="placeholder">{{ field.label_tag }}{{ field }}</li>
							{% else %}
								<li>{{ field.label_tag }}{{ field }}</li>
							{% endif %}

						{% endfor %}
				 	<input class="submit_button" type="submit" value="Заказать">
					</form>
				</div>
			{% endif %}


			{% if which_form == 'author' %}
				<div class="content order">
				<h1>Анкета автора</h1>
					<form name="" action="" method="POST"  enctype="multipart/form-data">{% csrf_token %}
						{% for field in form %}
							{% if field.name == 'name' %}<h1 class="prepare">Ваши ФИО</h1>{% endif %}
							{% if field.name == 'city' %}<h1 class="prepare">Контакты</h1>{% endif %}
							{% if field.name == 'vuz' %}<h1 class="prepare">Сведения об образовании</h1>{% endif %}
							{% if field.name == 'biznes_plan' %}<h1 class="prepare">Укажите уровни сложности (типы) работ, которые Вы могли бы выполнять:</h1>{% endif %}
							{% if field.name == 'design' %}<h1 class="prepare">Укажите направления, по которым Вы можете писать работы</h1><span class="helpiz">Гуманитарное</span>{% endif %}
							{% if field.name == 'astronomija' %}<span class="helpiz">Естественное</span>{% endif %}
							{% if field.name == 'vishka' %}<span class="helpiz">Техническое</span>{% endif %}
							{% if field.name == 'antikrizic' %}<span class="helpiz">Антикризисное управление</span>{% endif %}		
							
							{% if field.errors %}
								<li class="placeholder">{{ field.label_tag }}{{ field }}</li>
							{% else %}
								<li>{{ field.label_tag }}{{ field }}</li>
							{% endif %}

						{% endfor %}
				 	<input class="submit_button" type="submit" value="Заказать">
					</form>
				</div>
			{% endif %}



			{% if which_form == 'translate' %}
				<div class="content order">
				<h1>Анкета переводчика</h1>
					<form name="" action="" method="POST"  enctype="multipart/form-data">{% csrf_token %}
						{% for field in form %}
							{% if field.name == 'name' %}<h1 class="prepare">Ваши ФИО</h1>{% endif %}
							{% if field.name == 'city' %}<h1 class="prepare">Контакты</h1>{% endif %}
							{% if field.name == 'vuz' %}<h1 class="prepare">Сведения об образовании</h1>{% endif %}
							{% if field.name == 'stage' %}<h1 class="prepare">Опыт работы переводчиком</h1>{% endif %}
							{% if field.name == 'na_ino' %}<h1 class="prepare">Направления перевода</h1>{% endif %}
							{% if field.name == 'pismeni' %}<h1 class="prepare">Вид перевода</h1>{% endif %}
							{% if field.name == 'finansi' %}<h1 class="prepare">Предпочитаемые тематики переводов:</h1>{% endif %}
							{% if field.name == 'ustn_per' %}<h1 class="prepare">Желаемая зарплата</h1>{% endif %}
							{% if field.name == 'ustn_per_2' %}<h1 class="prepare">Минимальная зарплата</h1>{% endif %}
							{% if field.name == 'na_ino_lang' %}<h1 class="prepare">Работа в качестве редактора переводимых текстов</h1>{% endif %}
							
							{% if field.errors %}
								<li class="placeholder">{{ field.label_tag }}{{ field }}</li>
							{% else %}
								<li>{{ field.label_tag }}{{ field }}</li>
							{% endif %}

						{% endfor %}
				 	<input class="submit_button" type="submit" value="Заказать">
					</form>
				</div>
			{% endif %}
		{% endif %}
	{% endif %}
	</main>
{% endblock %}